### ISSUE TITLE
Cool stuff man, does it support low profile kailh keyswitch?

### ISSUE THREAD

**Issue by jmnguye** [keyzog/kapl#1]

**Comment by keyzog** [comment]
Thank you! Yes it support. 

But, keep in mind that spacing between switches is 19.1mm this is MX spacing. This is suitable for most keycaps (lowprofile too). But, if you are going to use MBK keycaps (17.5x16.5mm), then there will be an increased gap between them.

I have a plan make new pcb with spacing for MBK keycaps, but now don't have time for that.
