### ISSUE TITLE
Kailh sockets and recommended version

### ISSUE THREAD

**Issue by isavcic** [keyzog/kapl#2]
Hello,

Great looking keyboard, thanks for sharing it!

A couple of questions:

- Does the PCB support Kailh hotswap sockets?
- What is the recommended version, the one from the main branch or the revised one?

Thanks!

**Comment by keyzog** [comment]
Hello, thanks)
- in now pcb don't support hotswap. I have plan add hotswap, but not before a couple of months.
-  it's better to use the main branch version. I haven't tried soldering version 1.1 yet (pcb_rev branch). You can try it if you want, but at your own risk. But you can safely use [gerber__plate_bottom.zip](https://github.com/keyzog/kapl/blob/pcb_rev/gerbers/gerber__plate_bottom.zip) and [gerber__plate_top.zip](https://github.com/keyzog/kapl/blob/pcb_rev/gerbers/gerber__plate_top.zip) from the pcb_rev branch to create the case.

**Comment by keyzog** [comment]
**Remark to previous comment**

Added case pcbs in main branch, should have done it much sooner.
https://github.com/keyzog/kapl/wiki#from-pcb

And moved pcb v1.1 to dev branch, using also at your own risk.

**Comment by isavcic** [comment]
Thank you!
