### ISSUE TITLE
how to solder pro micro.

### ISSUE THREAD

**Issue by logicalbhanu** [keyzog/kapl#5]
Hi, thanks for this great project, i am trying to build it, but being noob in electrical stuff wouldn't be able to figure out how to solder the pro micro, as it is solder on the back of the pcb, with switches on on top it(on front side), can share some pictures of give some suggestion on how to do it.

**Comment by keyzog** [comment]
Hello! Hope this helps you: https://imgur.com/gallery/7m69tiw

If you have any questions, you can write to me at the contacts in my profile.

Don't forget to share a photo of the result 😉
