### ISSUE TITLE
no of m2 spacers

### ISSUE THREAD

**Issue by logicalbhanu** [keyzog/kapl#6]
hi, keyzog
me again(thanks for resolving my last issue), i want to know that in the list of materials you have mentioned the number of spacers as 18, but in the build guides one of the image, i am seeing only 9 spacers, here is the image
<img width="671" alt="image" src="https://github.com/keyzog/kapl/assets/40262328/a1f955b1-3fbc-4489-ac6c-e57379328f1d">
am i missing something(being a noob in this).

**Comment by keyzog** [comment]
Hi! 9 standoffs for left hand and 9 for right hand. Total 18pcs))

In general you can use 4 to 9 standoffs for one half. I added support 9 standoffs for the relatively soft materials of the top and bottom plate. If you made the plates from FR4, 4 standoffs are sufficient, but use more if possible.

**Comment by logicalbhanu** [comment]
thanks mate,my bad i didn't consider the left hand.
